name: Build-dotnet

on:
  workflow_call:
    inputs:
        dotnet-version:
            required: true
            type: string
        configuration:
            required: true
            type: string
        project-path:
          required: false
          type: string
          default: ""
        run-tests:
          required: false
          type: boolean
          default: false

jobs:
  build-dotnet:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore ${{ inputs.project-path }}
    - name: Build Config
      run: dotnet build ${{ inputs.project-path }} --no-restore --configuration ${{ inputs.configuration }}
    - name: Test Config
      if: ${{ success() && inputs.run-tests }}
      run: dotnet test ${{ inputs.project-path }} --no-build --configuration ${{ inputs.configuration }}
