name: Upload-Nuget-dotnet.yml

on:
  workflow_call:
    inputs:
        artifact-name:
          required: true
          type: string
        artifact-id:
          required: true
          type: string
        nuget-source:
          required: true
          type: string
    secrets:
      nuget-api-key:
        required: true

permissions:
  packages: write
  actions: read
  contents: read

jobs:
  push-package:
    runs-on: ubuntu-latest
    steps:
    - name: Download Package Artifact
      uses: actions/download-artifact@v4
      id: download-package
      with:
        name: ${{ inputs.artifact-name }}
        run-id: ${{ inputs.artifact-id }}

    - name: Push Nuget Package
      run: dotnet nuget push ${{ steps.download-package.outputs.download-path }}/*.nupkg --api-key ${{ secrets.nuget-api-key }} --source ${{ inputs.nuget-source }}
